CREATE TABLE Link (
  id BIGINT IDENTITY PRIMARY KEY,
  name NVARCHAR(255) NOT NULL,
  value NVARCHAR(255) NOT NULL,
  hotel_id BIGINT REFERENCES Hotel (id),
  link_order INT,
);

CREATE TABLE audit.Link_AUD (
  id BIGINT NOT NULL,
  name NVARCHAR(255),
  value NVARCHAR(255),
  REV BIGINT NOT NULL REFERENCES dbo.REVISION,
  REVTYPE SMALLINT,
  PRIMARY KEY (id, REV)
);

CREATE TABLE audit.Hotel_Link_AUD (
  id BIGINT NOT NULL,
  link_order INT NOT NULL,
  hotel_id BIGINT NOT NULL,
  REV BIGINT NOT NULL REFERENCES dbo.REVISION,
  REVTYPE SMALLINT,
  PRIMARY KEY (REV, hotel_id, id, link_order)
);