create table REVISION (rev bigint identity not null, timestamp bigint, primary key (rev));

create table audit.AvailableServices_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, bar_id bigint, breakfast_id bigint, carPark_id bigint, hairDresser_id bigint, housekeeping_id bigint, petCare_id bigint, rental_id bigint, restaurantMenu_id bigint, roomService_id bigint, spa_id bigint, spaCall_id bigint, tableOrdering_id bigint, taxi_id bigint, primary key (id, REV));
create table audit.Bar_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), fromHour varbinary(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, toHour varbinary(4000), primary key (id, REV));
create table audit.Bar_BarCategory_AUD (REV bigint not null, bar_id bigint not null, id bigint not null, category_order int not null, REVTYPE smallint, primary key (REV, bar_id, id, category_order));
create table audit.BarCategory_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, category nvarchar(4000), primary key (id, REV));
create table audit.BarCategory_BarItem_AUD (REV bigint not null, bar_category_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, bar_category_id, id));
create table audit.BarItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, available bit, name nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.BarOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, tableNumber nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.BarOrder_BarOrderItem_AUD (REV bigint not null, bar_order_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, bar_order_id, id));
create table audit.BarOrderItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, count int, item_id bigint, primary key (id, REV));
create table audit.Breakfast_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), fromHour varbinary(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, toHour varbinary(4000), primary key (id, REV));
create table audit.Breakfast_BreakfastCategory_AUD (REV bigint not null, breakfast_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, breakfast_id, id));
create table audit.BreakfastCategory_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, category nvarchar(4000), primary key (id, REV));
create table audit.BreakfastCategory_BreakfastItem_AUD (REV bigint not null, breakfast_category_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, breakfast_category_id, id));
create table audit.BreakfastItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, available bit, name nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.BreakfastOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, time varbinary(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.BreakfastOrder_BreakfastOrderItem_AUD (REV bigint not null, breakfast_order_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, breakfast_order_id, id));
create table audit.BreakfastOrderItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, count int, item_id bigint, primary key (id, REV));
create table audit.CarPark_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.CarParkOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, fromDate varbinary(4000), licenseNumber nvarchar(4000), toDate varbinary(4000), primary key (id, REV));
create table audit.CubilisConnectionStatus_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, status nvarchar(4000), primary key (id, REV));
create table audit.CubilisCustomer_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, email nvarchar(4000), firstName nvarchar(4000), lastName nvarchar(4000), primary key (id, REV));
create table audit.CubilisReservation_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, arrival varbinary(4000), departure varbinary(4000), guestCount int, isRejected bit, status nvarchar(4000), customer_id bigint, guest_id bigint, hotel_id bigint, primary key (id, REV));
create table audit.CubilisSettings_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, isEnabled bit, isMergingEnabled bit, login nvarchar(4000), password nvarchar(4000), primary key (id, REV));
create table audit.DndOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, status nvarchar(4000), primary key (id, REV));
create table audit.FileLink_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, filename nvarchar(4000), url nvarchar(4000), primary key (id, REV));
create table audit.Guest_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, email nvarchar(4000), firstName nvarchar(4000), identification nvarchar(4000), lastName nvarchar(4000), nationality nvarchar(4000), primary key (id, REV));
create table audit.GuestAccount_AUD (username nvarchar(4000) not null, REV bigint not null, REVTYPE smallint, primary key (username, REV));
create table audit.HairDresser_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), number nvarchar(4000), primary key (id, REV));
create table audit.Hotel_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, address nvarchar(4000), bookingUrl nvarchar(4000), chain nvarchar(4000), currency nvarchar(4000), description nvarchar(4000), email nvarchar(4000), eventsUrl nvarchar(4000), fax nvarchar(4000), interestingPlacesUrl nvarchar(4000), isMarkedAsDeleted bit, isTestHotel bit, isThrodiPartner bit, latitude double precision, longitude double precision, meteoUrl nvarchar(4000), name nvarchar(4000), phone nvarchar(4000), propertyType nvarchar(4000), ratingOverall real, ratingOverallText nvarchar(4000), restaurantsUrl nvarchar(4000), rooms int, shopsUrl nvarchar(4000), starRating real, website nvarchar(4000), availableServices_id bigint, cubilisConnectionStatus_id bigint, cubilisSettings_id bigint, notificationSettings_id bigint, roomDirectory_id bigint, usefulInformation_id bigint, primary key (id, REV));
create table audit.Hotel_FileLink_AUD (REV bigint not null, hotel_id bigint not null, id bigint not null, filelink_order int not null, REVTYPE smallint, primary key (REV, hotel_id, id, filelink_order));
create table audit.Hotel_Guest_AUD (REV bigint not null, Hotel_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, Hotel_id, id));
create table audit.Housekeeping_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.Housekeeping_HousekeepingItem_AUD (REV bigint not null, housekeeping_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, housekeeping_id, id));
create table audit.housekeeping_order_housekeeping_item_AUD (REV bigint not null, housekeeping_order_id bigint not null, housekeeping_item_id bigint not null, REVTYPE smallint, primary key (REV, housekeeping_order_id, housekeeping_item_id));
create table audit.HousekeepingItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, name nvarchar(4000), primary key (id, REV));
create table audit.HousekeepingOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, message nvarchar(4000), primary key (id, REV));
create table audit.NotificationSettings_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, bar bit, breakfast bit, carPark bit, email nvarchar(4000), housekeeping bit, petCare bit, rental bit, roomService bit, spa bit, tableOrdering bit, taxi bit, primary key (id, REV));
create table audit.Orders_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, dnd_id bigint, primary key (id, REV));
create table audit.Orders_BarOrder_AUD (REV bigint not null, orders_id_bar bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_bar, id));
create table audit.Orders_BreakfastOrder_AUD (REV bigint not null, orders_id_breakfast bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_breakfast, id));
create table audit.Orders_CarParkOrder_AUD (REV bigint not null, orders_id_car_park bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_car_park, id));
create table audit.Orders_HousekeepingOrder_AUD (REV bigint not null, orders_id_housekeeping bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_housekeeping, id));
create table audit.Orders_PetCareOrder_AUD (REV bigint not null, orders_id_pet_care bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_pet_care, id));
create table audit.Orders_RentalOrder_AUD (REV bigint not null, orders_id_rental bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_rental, id));
create table audit.Orders_RoomServiceOrder_AUD (REV bigint not null, orders_id_room_service bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_room_service, id));
create table audit.Orders_SpaOrder_AUD (REV bigint not null, orders_id_spa bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_spa, id));
create table audit.Orders_TableOrderingOrder_AUD (REV bigint not null, orders_id_tableordering bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_tableordering, id));
create table audit.Orders_TaxiOrder_AUD (REV bigint not null, orders_id_taxi bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, orders_id_taxi, id));
create table audit.PetCare_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.PetCare_PetCareItem_AUD (REV bigint not null, pet_care_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, pet_care_id, id));
create table audit.PetCareItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), name nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.PetCareOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, date varbinary(4000), item_id bigint, primary key (id, REV));
create table audit.Rental_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), fromHour varbinary(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, toHour varbinary(4000), primary key (id, REV));
create table audit.Rental_RentalCategory_AUD (REV bigint not null, rental_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, rental_id, id));
create table audit.RentalCategory_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, category nvarchar(4000), primary key (id, REV));
create table audit.RentalCategory_RentalItem_AUD (REV bigint not null, rental_category_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, rental_category_id, id));
create table audit.RentalItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, available bit, name nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.RentalOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, createdAt datetime2, time varbinary(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.RentalOrder_RentalOrderItem_AUD (REV bigint not null, rental_order_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, rental_order_id, id));
create table audit.RentalOrderItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, count int, item_id bigint, primary key (id, REV));
create table audit.RestaurantMenu_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), primary key (id, REV));
create table audit.RestaurantMenu_RestaurantMenuCategory_AUD (REV bigint not null, restaurant_menu_id bigint not null, id bigint not null, category_order int not null, REVTYPE smallint, primary key (REV, restaurant_menu_id, id, category_order));
create table audit.RestaurantMenuCategory_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, name nvarchar(4000), primary key (id, REV));
create table audit.RestaurantMenuCategory_RestaurantMenuItem_AUD (REV bigint not null, restaurant_menu_category_id bigint not null, id bigint not null, item_order int not null, REVTYPE smallint, primary key (REV, restaurant_menu_category_id, id, item_order));
create table audit.RestaurantMenuItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), name nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.RoomDirectory_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, primary key (id, REV));
create table audit.RoomDirectory_Section_AUD (REV bigint not null, room_directory_id bigint not null, id bigint not null, sections_order int not null, REVTYPE smallint, primary key (REV, room_directory_id, id, sections_order));
create table audit.RoomService_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.RoomService_RoomServiceCategory_AUD (REV bigint not null, room_service_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, room_service_id, id));
create table audit.RoomServiceCategory_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, category nvarchar(4000), primary key (id, REV));
create table audit.RoomServiceCategory_RoomServiceItem_AUD (REV bigint not null, room_service_category_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, room_service_category_id, id));
create table audit.RoomServiceItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, available bit, name nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.RoomServiceOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, time varbinary(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.RoomServiceOrder_RoomServiceOrderItem_AUD (REV bigint not null, room_service_order_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, room_service_order_id, id));
create table audit.RoomServiceOrderItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, count int, item_id bigint, primary key (id, REV));
create table audit.SalesmanAccount_AUD (username nvarchar(4000) not null, REV bigint not null, REVTYPE smallint, password nvarchar(4000), primary key (username, REV));
create table audit.SalesmanAccount_roles_AUD (REV bigint not null, SalesmanAccount_username nvarchar(4000) not null, roles nvarchar(4000) not null, REVTYPE smallint, primary key (REV, SalesmanAccount_username, roles));
create table audit.Section_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, heading nvarchar(4000), text nvarchar(4000), primary key (id, REV));
create table audit.Spa_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.Spa_SpaItem_AUD (REV bigint not null, spa_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, spa_id, id));
create table audit.SpaCalendar_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, primary key (id, REV));
create table audit.SpaCalendar_SpaCalendarDay_AUD (REV bigint not null, spa_calendar_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, spa_calendar_id, id));
create table audit.SpaCalendarDay_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, day varbinary(4000), primary key (id, REV));
create table audit.SpaCalendarDay_SpaCalendarHour_AUD (REV bigint not null, spa_calendar_day_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, spa_calendar_day_id, id));
create table audit.SpaCalendarHour_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, available bit, hour varbinary(4000), primary key (id, REV));
create table audit.SpaCall_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), number nvarchar(4000), primary key (id, REV));
create table audit.SpaItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, name nvarchar(4000), currency nvarchar(4000), text nvarchar(4000), value decimal, calendar_id bigint, primary key (id, REV));
create table audit.SpaOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, time varbinary(4000), item_id bigint, primary key (id, REV));
create table audit.Stay_AUD (pin nvarchar(4000) not null, REV bigint not null, REVTYPE smallint, createdAt datetime2, cubilisId bigint, doorKey nvarchar(4000), fromDate varbinary(4000), roomNumber nvarchar(4000), status nvarchar(4000), toDate varbinary(4000), wifiPassword nvarchar(4000), guest_id bigint, hotel_id bigint, orders_id bigint, primary key (pin, REV));
create table audit.TableOrdering_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, description nvarchar(4000), primary key (id, REV));
create table audit.TableOrderingOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, numberOfPeople int, time varbinary(4000), primary key (id, REV));
create table audit.Taxi_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, currency nvarchar(4000), text nvarchar(4000), value decimal, primary key (id, REV));
create table audit.Taxi_TaxiItem_AUD (REV bigint not null, taxi_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, taxi_id, id));
create table audit.TaxiItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, name nvarchar(4000), number nvarchar(4000), primary key (id, REV));
create table audit.TaxiOrder_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, destination nvarchar(4000), numberOfPeople int, time varbinary(4000), primary key (id, REV));
create table audit.UsefulInformation_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, primary key (id, REV));
create table audit.UsefulInformation_UsefulInformationHourItem_AUD (REV bigint not null, hours_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, hours_id, id));
create table audit.UsefulInformation_UsefulInformationOtherItem_AUD (REV bigint not null, other_id bigint not null, id bigint not null, REVTYPE smallint, primary key (REV, other_id, id));
create table audit.UsefulInformationHourItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, fromHour varbinary(4000), name nvarchar(4000), toHour varbinary(4000), primary key (id, REV));
create table audit.UsefulInformationOtherItem_AUD (id bigint not null, REV bigint not null, REVTYPE smallint, name nvarchar(4000), value nvarchar(4000), primary key (id, REV));
create table audit.UserAccount_AUD (username nvarchar(4000) not null, REV bigint not null, REVTYPE smallint, hotelId bigint, password nvarchar(4000), primary key (username, REV));
create table audit.UserAccount_roles_AUD (REV bigint not null, UserAccount_username nvarchar(4000) not null, roles nvarchar(4000) not null, REVTYPE smallint, primary key (REV, UserAccount_username, roles));
create table audit.UserAccountPending_AUD (email nvarchar(4000) not null, REV bigint not null, REVTYPE smallint, hotelId bigint, password nvarchar(4000), redirectUrl nvarchar(4000), secret nvarchar(4000), primary key (email, REV));

alter table audit.AvailableServices_AUD add constraint FKevc1665yqrpn4awke6ltp5qif foreign key (REV) references REVISION;
alter table audit.Bar_AUD add constraint FKh7pxk6sh3esgidr3tiwvy6b69 foreign key (REV) references REVISION;
alter table audit.Bar_BarCategory_AUD add constraint FKqta9gk0b2j73a5e9x12oql6ls foreign key (REV) references REVISION;
alter table audit.BarCategory_AUD add constraint FKlhdsyavorpm2rh5qgdxx36wcy foreign key (REV) references REVISION;
alter table audit.BarCategory_BarItem_AUD add constraint FKnvnff3ocnljoniuv3j07dgfmf foreign key (REV) references REVISION;
alter table audit.BarItem_AUD add constraint FKmjh1yr8hgad9hilbac495u8et foreign key (REV) references REVISION;
alter table audit.BarOrder_AUD add constraint FK5a4j7k9l68ad8de63s3fnootc foreign key (REV) references REVISION;
alter table audit.BarOrder_BarOrderItem_AUD add constraint FK25mdmr7fqslrbaoidypplnfol foreign key (REV) references REVISION;
alter table audit.BarOrderItem_AUD add constraint FKax2fbjrvxx6ad7knlj881itd4 foreign key (REV) references REVISION;
alter table audit.Breakfast_AUD add constraint FK3u9kov9qs7awmvbcb18tpenxm foreign key (REV) references REVISION;
alter table audit.Breakfast_BreakfastCategory_AUD add constraint FKgbe5ftl4ttsfhsi11fwupm5d foreign key (REV) references REVISION;
alter table audit.BreakfastCategory_AUD add constraint FKhveivlo2qdqjrmojx0gjgst4b foreign key (REV) references REVISION;
alter table audit.BreakfastCategory_BreakfastItem_AUD add constraint FKbqcg4js840p9jdd512pbaux4j foreign key (REV) references REVISION;
alter table audit.BreakfastItem_AUD add constraint FK229ru9xrknewmvudl27igru85 foreign key (REV) references REVISION;
alter table audit.BreakfastOrder_AUD add constraint FKtfp97u7gkvprlqxwl9xa1ycgv foreign key (REV) references REVISION;
alter table audit.BreakfastOrder_BreakfastOrderItem_AUD add constraint FK2i0dprv38aiqam1r88yk3hph7 foreign key (REV) references REVISION;
alter table audit.BreakfastOrderItem_AUD add constraint FK62n0ajprgj4ebjhmpghwhqy1p foreign key (REV) references REVISION;
alter table audit.CarPark_AUD add constraint FKtin65dut26s001pud0l6ivuw3 foreign key (REV) references REVISION;
alter table audit.CarParkOrder_AUD add constraint FK4mobd6fq1241v3tqfwk4l5w0p foreign key (REV) references REVISION;
alter table audit.CubilisConnectionStatus_AUD add constraint FKfrm3phpgq68kyqipckgti9ey4 foreign key (REV) references REVISION;
alter table audit.CubilisCustomer_AUD add constraint FKbb4v5ukyedxjkkplfb8uarv6q foreign key (REV) references REVISION;
alter table audit.CubilisReservation_AUD add constraint FKmvhw8xr2wot855fnqxbq50uw8 foreign key (REV) references REVISION;
alter table audit.CubilisSettings_AUD add constraint FKoy5fil5h3tqitq7w2u671e89s foreign key (REV) references REVISION;
alter table audit.DndOrder_AUD add constraint FK933qhajwi7cm4waa7ry7fqv0c foreign key (REV) references REVISION;
alter table audit.FileLink_AUD add constraint FKm83c5gvvw54rlt68osb7oqis3 foreign key (REV) references REVISION;
alter table audit.Guest_AUD add constraint FK2a67jnbs38pcn5xrgx2yr4h3p foreign key (REV) references REVISION;
alter table audit.GuestAccount_AUD add constraint FKej6pdmv8gmmpxd718f9q2ohca foreign key (REV) references REVISION;
alter table audit.HairDresser_AUD add constraint FKdv9kpvwvslnydfqdwablndr0r foreign key (REV) references REVISION;
alter table audit.Hotel_AUD add constraint FKaerpreak6laljatfkycu3as86 foreign key (REV) references REVISION;
alter table audit.Hotel_FileLink_AUD add constraint FKajwf2xn3axffd29f9opx541c1 foreign key (REV) references REVISION;
alter table audit.Hotel_Guest_AUD add constraint FKir5x0d0b1ius402iwsjbmc8dl foreign key (REV) references REVISION;
alter table audit.Housekeeping_AUD add constraint FKrib13joube2bkcfenged1iqh0 foreign key (REV) references REVISION;
alter table audit.Housekeeping_HousekeepingItem_AUD add constraint FKd2j69p10o3firkybocojsc6dj foreign key (REV) references REVISION;
alter table audit.housekeeping_order_housekeeping_item_AUD add constraint FKmmxv1ujqyl005kq5sv4id5dho foreign key (REV) references REVISION;
alter table audit.HousekeepingItem_AUD add constraint FK7vhswhv50gb7pej02a7ss3e9y foreign key (REV) references REVISION;
alter table audit.HousekeepingOrder_AUD add constraint FK7kfotrwwcnhph9vt4l2pcf2ae foreign key (REV) references REVISION;
alter table audit.NotificationSettings_AUD add constraint FKbjwwjte094ylrarc57nbv3hps foreign key (REV) references REVISION;
alter table audit.Orders_AUD add constraint FKqyvu6d47ksal5qpfkc403jcft foreign key (REV) references REVISION;
alter table audit.Orders_BarOrder_AUD add constraint FKh5igcf10ie1kpwe0qw9mk44nj foreign key (REV) references REVISION;
alter table audit.Orders_BreakfastOrder_AUD add constraint FKdm0bsd7cmnq72kh9pd9lvg3eu foreign key (REV) references REVISION;
alter table audit.Orders_CarParkOrder_AUD add constraint FKq2d8stq604488axjn3mllh929 foreign key (REV) references REVISION;
alter table audit.Orders_HousekeepingOrder_AUD add constraint FKoexe3o8vlijfu5kqou2k5hfor foreign key (REV) references REVISION;
alter table audit.Orders_PetCareOrder_AUD add constraint FK4d6625ip0tc0inw0rejo9gdt8 foreign key (REV) references REVISION;
alter table audit.Orders_RentalOrder_AUD add constraint FKji7vx3lyv8ffbsqcsbd6j8ftd foreign key (REV) references REVISION;
alter table audit.Orders_RoomServiceOrder_AUD add constraint FKysdv4o75traq98yi2ef9u0gf foreign key (REV) references REVISION;
alter table audit.Orders_SpaOrder_AUD add constraint FKaj4t8k8fnl9i9jhg1h420symm foreign key (REV) references REVISION;
alter table audit.Orders_TableOrderingOrder_AUD add constraint FKavrb67p8yinodhmyq64e36dnf foreign key (REV) references REVISION;
alter table audit.Orders_TaxiOrder_AUD add constraint FKps30ef0qcs8e7wf9jqwnqwy77 foreign key (REV) references REVISION;
alter table audit.PetCare_AUD add constraint FKi81w5j074f4k9cim83p0xoype foreign key (REV) references REVISION;
alter table audit.PetCare_PetCareItem_AUD add constraint FKkr8athg2q3im84xlg7cvdn0un foreign key (REV) references REVISION;
alter table audit.PetCareItem_AUD add constraint FKdab4hfi3rlhkle5bkorfuia9a foreign key (REV) references REVISION;
alter table audit.PetCareOrder_AUD add constraint FKred5rrm4svh90f0st6ce7bx9l foreign key (REV) references REVISION;
alter table audit.Rental_AUD add constraint FK320dnmnw06r3fjkdl82gxbl1r foreign key (REV) references REVISION;
alter table audit.Rental_RentalCategory_AUD add constraint FKbqdcs0k57h6osp2pkfb5e8q28 foreign key (REV) references REVISION;
alter table audit.RentalCategory_AUD add constraint FKrl5gq3m6djs1jho4fv7er9vop foreign key (REV) references REVISION;
alter table audit.RentalCategory_RentalItem_AUD add constraint FK6weg1n5m2xy6dgn2pyr2ewwmf foreign key (REV) references REVISION;
alter table audit.RentalItem_AUD add constraint FKahsvmk99ipo07mwppl5aqutpo foreign key (REV) references REVISION;
alter table audit.RentalOrder_AUD add constraint FKjt5s4q6kvwy3md907e5me7u1l foreign key (REV) references REVISION;
alter table audit.RentalOrder_RentalOrderItem_AUD add constraint FKdfvd45nwncs1ja3965mcb325r foreign key (REV) references REVISION;
alter table audit.RentalOrderItem_AUD add constraint FK4urp5cipvo3a4ikdp6iveenkt foreign key (REV) references REVISION;
alter table audit.RestaurantMenu_AUD add constraint FKrobwvc3s1xugwctmk24iya0kn foreign key (REV) references REVISION;
alter table audit.RestaurantMenu_RestaurantMenuCategory_AUD add constraint FKe6wa586ue2v1w86p4tg213m3x foreign key (REV) references REVISION;
alter table audit.RestaurantMenuCategory_AUD add constraint FKk9f7v8f8m3r3t1uf117wqnttc foreign key (REV) references REVISION;
alter table audit.RestaurantMenuCategory_RestaurantMenuItem_AUD add constraint FKftlajgdbpa8m2qvfmlu5xqd1b foreign key (REV) references REVISION;
alter table audit.RestaurantMenuItem_AUD add constraint FKthnqn6mf0gnc9t3ubfbiwejjp foreign key (REV) references REVISION;
alter table audit.RoomDirectory_AUD add constraint FKalhe9hya2pswyrdl6ugx3c72c foreign key (REV) references REVISION;
alter table audit.RoomDirectory_Section_AUD add constraint FKb1049835vvmcui2reu7pelx8x foreign key (REV) references REVISION;
alter table audit.RoomService_AUD add constraint FK6b6dolj88e0k9rfjbpgrab8rx foreign key (REV) references REVISION;
alter table audit.RoomService_RoomServiceCategory_AUD add constraint FKj9kmvm1qdbb66v5hs1w1fuf2y foreign key (REV) references REVISION;
alter table audit.RoomServiceCategory_AUD add constraint FK5aab1wgsnp0kmliq9ls86rwhv foreign key (REV) references REVISION;
alter table audit.RoomServiceCategory_RoomServiceItem_AUD add constraint FK21c3iaw8o8rkde53gy0b8s9q9 foreign key (REV) references REVISION;
alter table audit.RoomServiceItem_AUD add constraint FK591ognoeiayay8stcxn291d14 foreign key (REV) references REVISION;
alter table audit.RoomServiceOrder_AUD add constraint FKclum21bdmq62ld6pjqyiwaqyi foreign key (REV) references REVISION;
alter table audit.RoomServiceOrder_RoomServiceOrderItem_AUD add constraint FKjicl298bj5u1f1fyq9ryov66u foreign key (REV) references REVISION;
alter table audit.RoomServiceOrderItem_AUD add constraint FK7ikucxs7ow27455b8kf4k0591 foreign key (REV) references REVISION;
alter table audit.SalesmanAccount_AUD add constraint FKirx6ot1swxmuuap3n7nqe5kay foreign key (REV) references REVISION;
alter table audit.SalesmanAccount_roles_AUD add constraint FKk3qs6rnj9cbimpv44oh0grm4o foreign key (REV) references REVISION;
alter table audit.Section_AUD add constraint FKpeyjaj35qeqk635mdj6pblcgy foreign key (REV) references REVISION;
alter table audit.Spa_AUD add constraint FKqd45m6b81s2tnjdx8ixd9upjj foreign key (REV) references REVISION;
alter table audit.Spa_SpaItem_AUD add constraint FKap6vp5sb6u4ac5r7yr6v7v693 foreign key (REV) references REVISION;
alter table audit.SpaCalendar_AUD add constraint FKcikg5j6wln8ggbgps5uhf5ac8 foreign key (REV) references REVISION;
alter table audit.SpaCalendar_SpaCalendarDay_AUD add constraint FK3bnshcurl8a64tft3m5ock42a foreign key (REV) references REVISION;
alter table audit.SpaCalendarDay_AUD add constraint FKdxj6e1xhbqlw9ng73qbrwr8m7 foreign key (REV) references REVISION;
alter table audit.SpaCalendarDay_SpaCalendarHour_AUD add constraint FKqr7xt3njl6om19bcl46ha1aok foreign key (REV) references REVISION;
alter table audit.SpaCalendarHour_AUD add constraint FK9q0qhwqy8ydh6f0rvfjjao7ho foreign key (REV) references REVISION;
alter table audit.SpaCall_AUD add constraint FKi53qh893o03jwjasdrkymrvfg foreign key (REV) references REVISION;
alter table audit.SpaItem_AUD add constraint FKfxwunq0njll87sd6isahwgpf8 foreign key (REV) references REVISION;
alter table audit.SpaOrder_AUD add constraint FKlpk409yb5aa27yjpvlrsvkv3w foreign key (REV) references REVISION;
alter table audit.Stay_AUD add constraint FKqoonynwwr6x7anwvmifv8yroj foreign key (REV) references REVISION;
alter table audit.TableOrdering_AUD add constraint FKinm4tbq2cho5q4mlwledi980n foreign key (REV) references REVISION;
alter table audit.TableOrderingOrder_AUD add constraint FK2a241i2cctdg1ogk88ck9w5yx foreign key (REV) references REVISION;
alter table audit.Taxi_AUD add constraint FKasb4faetxq95gub33fs8336le foreign key (REV) references REVISION;
alter table audit.Taxi_TaxiItem_AUD add constraint FKk473hfj86o4mennbedv23dk5u foreign key (REV) references REVISION;
alter table audit.TaxiItem_AUD add constraint FKcb9mojv5u1m23c66xi26fetjm foreign key (REV) references REVISION;
alter table audit.TaxiOrder_AUD add constraint FKhojpi4dlxrjdi3odgo3ilng0a foreign key (REV) references REVISION;
alter table audit.UsefulInformation_AUD add constraint FKhj300niqgxiw5020r1grcb0dt foreign key (REV) references REVISION;
alter table audit.UsefulInformation_UsefulInformationHourItem_AUD add constraint FK3mtp944pkcirxb8mri3g3dfw8 foreign key (REV) references REVISION;
alter table audit.UsefulInformation_UsefulInformationOtherItem_AUD add constraint FKow6thib5xdnowgf9p7y8xs956 foreign key (REV) references REVISION;
alter table audit.UsefulInformationHourItem_AUD add constraint FKby3fyushgjrd6ubjgvpclup2i foreign key (REV) references REVISION;
alter table audit.UsefulInformationOtherItem_AUD add constraint FK7jq4xx8lc2hcjv6ppu24a1ay7 foreign key (REV) references REVISION;
alter table audit.UserAccount_AUD add constraint FKpqns3m0y7f5sbgi7sjd9eek7g foreign key (REV) references REVISION;
alter table audit.UserAccount_roles_AUD add constraint FK3qs2vdgqr8pk230o4bqoq2cul foreign key (REV) references REVISION;
alter table audit.UserAccountPending_AUD add constraint FK8dki2vksgp0imx5ogqtr45l3c foreign key (REV) references REVISION;
